services:
  nginx:
    image: nginx:1.25-alpine
    container_name: yii2-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - yii2-network

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: yii2-php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - yii2-network
    environment:
      - DB_HOST=mysql
      - DB_NAME=yii2_books
      - DB_USER=yii2_user
      - DB_PASSWORD=password123

  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2_books
      MYSQL_USER: yii2_user
      MYSQL_PASSWORD: password123
    ports:
      - "33061:33061"
    volumes:
      - mysql_data:/var/lib/mysql
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - yii2-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii2-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: yii2_user
      PMA_PASSWORD: password123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - yii2-network

volumes:
  mysql_data:

networks:
  yii2-network:
    driver: bridge